### ISSUE TITLE
Possible unintentional bug in LFI-3?

### ISSUE THREAD

**Issue by frankfarmer** [paralax/lfi-labs#10]
https://github.com/paralax/lfi-labs/commit/3d02078c59585d6b8ca72b53c10a7fdc3a61fc19#commitcomment-22818897

The form method is GET, but the code references $_POST, so the script does nothing unless you tamper with the form.  Is this an intentional bug?

**Comment by frankfarmer** [comment]
https://github.com/paralax/lfi-labs/blob/master/LFI-8/index.php

LFI-8 contains a smilar GET/POST mismatch

(I'd be glad to correct these in a PR if they are indeed not intentional bugs)

**Comment by paralax** [comment]
yep, those are bugs. nice catches :) happy to take a PR if you're feeling interested, otherwise i can do it.

**Comment by paralax** [comment]
thanks, @frankfarmer, nice catches! all fixed i hope. 

Dockerhub should also auto-update with the github hook.
