### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dalpan** [paralax/lfi-labs#13]
Hi,

the repository doesnt contain a license file, without it nobody is allowed to use your project: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Could you please add a license?

Thx,
Dalpan

**Comment by paralax** [comment]
huh? MIT license. see the file LICENSE ... 

https://github.com/paralax/lfi-labs/blob/master/LICENSE 

closing, this isn't an issue.
