### ISSUE TITLE
is_set not a valid method in PHP

### ISSUE THREAD

**Issue by youanden** [paralax/lfi-labs#2]
Did you mean `isset` [here](https://github.com/paralax/lfi-labs/blob/master/HDR-1/index.php#L7)?

Would it be better to use `array_key_exists` for this purpose or not necessary because PHP always initialized `$_COOKIE` to an array/object?

**Comment by paralax** [comment]
thank you, fixed in 23cad17

**Comment by paralax** [comment]
thank you again! it's been eons since i wrote much PHP, so i'm sure bugs like this exist. it was just so easy to commit various security flaws with PHP so i chose it.
